service: mkai-goku-service

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-7
  stage: dev

plugins:
  - serverless-dotenv-plugin

functions:
  app:
    handler: app.main.lambda_handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

package:
  patterns:
    - '!node_modules/**'
    - '!__pycache__/**'
    - 'app/**'
    - 'requirements.txt'
    - '!tests/**'
