service: mkai-goku-service

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-1
  stage: dev
  ecr:
    images:
      mkai-goku-service-app:
        path: .

plugins:
  - serverless-dotenv-plugin

functions:
  app:
    image:
      name: mkai-goku-service-app
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

package:
  patterns:
    - '!node_modules/**'
    - '!__pycache__/**'
    - 'app/**'
    - 'requirements.txt'
    - '!tests/**'
