name: Deploy Lambda Function

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-7
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 778812951593.dkr.ecr.ap-southeast-7.amazonaws.com
        ECR_REPOSITORY: serverless-mkai-goku-api-service-dev
        IMAGE_TAG: latest
      run: |
        docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Serverless Framework
      run: npm install -g serverless
      
    - name: Install serverless-dotenv-plugin
      run: npm install serverless-dotenv-plugin
      
    - name: Deploy to AWS Lambda
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        API_URL: ${{ secrets.API_URL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: serverless deploy --stage dev
