name: Deploy Lambda

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies to temporary folder
        run: |
          mkdir -p build
          pip install -r requirements.txt -t build
          cp -r app/* build/

      - name: Zip deployment package
        run: |
          cd build
          zip -r ../lambda_function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:ap-southeast-2:712137513056:function:mkai-goku-service \
            --zip-file fileb://lambda_function.zip

