name: Deploy Lambda

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Lambda package in Amazon Linux Docker
        run: |
          docker run --rm -v "$PWD/mkai-goku-service":/app -w /app amazonlinux:2 \
            /bin/bash -c "
              yum install -y python3 python3-pip zip && \
              python3 -m pip install --upgrade pip && \
              python3 -m pip install -r requirements.txt -t /app/build && \
              cp -r app/* /app/build/ && \
              cd /app/build && \
              zip -r /app/lambda_function.zip .
            "



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name mkai-goku-service \
            --zip-file fileb://lambda_function.zip
