name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t package
          cp -r app/* package/
          cd package && zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda
        run: |
          # Try to update the function code, if it doesn't exist, create it
          aws lambda update-function-code --function-name mkai-goku-service --zip-file fileb://lambda.zip || \
          aws lambda create-function --function-name mkai-goku-service \
            --runtime python3.10 \
            --role arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_LAMBDA_ROLE \
            --handler app.handler \
            --zip-file fileb://lambda.zip \
            --timeout 15 \
            --memory-size 128 

      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name mkai-goku-service \
            --environment "Variables={${{ secrets.LAMBDA_ENV_VARS }}}"